reachagoal/config/routes.rb
Reachagoal::Application.routes.draw do

  resources :currencies

  resources :moneyboxes

  resources :friends

  resources :categories

  devise_for :users
  
  resources :objectives, except: :index
  
  
  unauthenticated :user do
 	  root :to => "public#index", :as => "unauthenticated"
   end
 
  authenticated :user do
  	root :to => "private#user_dashboard" 
  end
  
  get "dashboard" => "private#user_dashboard"
  post "/objectives/:objective_id/add_value" => "objectives#add_value", :as => "add_value"
  post "/objectives/:objective_id/add_comment" => "objectives#add_comment", :as => "add_comment"
  post "/objectives/:objective_id/add_friend/:friend_id" => "objectives#add_friend", :as=>"add_friend_objective"


  get "remove_value/:id" => "objectives#remove_value", :as=>"remove_value"
  get "remove_comment/:id" => "objectives#remove_comment", :as=>"remove_comment"

  get "public/index" 
  

  get "publicprofile/:id" => "private#public_profile", :as=>"public_profile"

  post "publicprofile/add_badge/:friend_id" => "private#add_badge", :as=>"add_badge"

  post "add_friend/" => "private#add_friend", :as=>"add_friend_email"
  get "add_friend/:id" => "private#add_friend", :as=>"add_friend"
  get "remove_friend/:id" => "private#remove_friend", :as=>"remove_friend"
  
  get "ajax_challenges/:id" => "private#ajax_challenges"
  get "ajax_challenges" => "private#ajax_challenges"

  get "ajax_values/:id" => "objectives#ajax_values"
  get "ajax_badges/:id" => "private#ajax_badges"
  get "ajax_badges/" => "private#ajax_badges"
    
  get "ajax_friends/:id" => "private#ajax_friends"
  get "ajax_friends/" => "private#ajax_friends"
  
  
  
end

reachagoal/app/models/badge.rb
class Badge < ActiveRecord::Base
	has_many :user_badges

end

reachagoal/app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :objective

end

reachagoal/app/models/currency.rb
class Currency < ActiveRecord::Base
end

reachagoal/app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => 'User', :foreign_key => 'friend_id'
	
	
	def Friend.is_friend?(user_id, friend_id)
		return !Friend.where("user_id=? and friend_id=? and state=?", user_id, friend_id, "1" ).blank?
	end

	
end

reachagoal/app/models/moneybox.rb
class Moneybox < ActiveRecord::Base
end

reachagoal/app/models/objective.rb
class Objective < ActiveRecord::Base
    has_attached_file :photo,
      :styles => { :wide => "1440x900#", :dashboard => "500x300#", :thumb_obj => "200x125#" },
      :convert_options => { :wide => "-blur 0x5" },
      :default_url => "/assets/objective/:style/placeholder.jpg",
      :url => "/system/objectives/:attachment/:id/:style/:filename",
      
      :path => ":rails_root/public/system/objectives/:attachment/:id/:style/:filename"
      
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	has_many :objective_values
	has_many :user_objectives	
	has_many :objective_comments
	
	  validates_presence_of :name
	  validates_presence_of :price
	  validates_presence_of :objective_type
	  validates_presence_of :category_id
	  validates :price, numericality: true


	
	def missing_value
	  if objective_values.length>0
	  	price - objective_values.map { |o| o.value }.inject{|sum,x| sum + x }
	  else
	   price
	  end
	end

	def completed_percentage 
		return (((self.price-self.missing_value)/self.price)*100)
	end
	
	def missing_value_shared(user_id)
		if objective_values.length>0
			users= objective_values.map{|obj| obj.user_id}
			values = objective_values.map{|obj| obj.value}	
			hash = Hash[users.uniq.map{|v| [v,0]}]
			users.each_with_index{|v,i| hash[v] = hash[v] + values[i] }
			values_user = Hash[hash.sort_by{|k,v| v}.reverse]
			if values_user[user_id].blank?
				return price
			else	
				return price-values_user[user_id]
			end
		else
			return price
		end
	end
	
	def completed_percentage_shared(user_id)
		completed = ((self.price-self.missing_value_shared(user_id))/self.price)*100
		
		if completed.blank?
			return 0
		else 
			return completed
		end
		
		 
	end
end

reachagoal/app/models/objective_comment.rb
class ObjectiveComment < ActiveRecord::Base

  belongs_to :user
  belongs_to :objective
end

reachagoal/app/models/objective_value.rb
class ObjectiveValue < ActiveRecord::Base

  belongs_to :user
  belongs_to :objective
  validates_presence_of :value
  validates :value, numericality: true
  
end

reachagoal/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   
   has_attached_file :photo,
      :styles => { :wide => "1000x400#", :dashboard => "180x220#", :thumb => "100x100#", :nav => "60x60#" },
      :default_url => "/assets/user/:style/placeholder.jpg",
      :url => "/system/user/:attachment/:id/:style/:filename",
      
      :path => ":rails_root/public/system/user/:attachment/:id/:style/:filename"
      
   has_attached_file :cover,
      :styles => { :cover => "1500x500#", :cover_thumb => "300x100#"},
      :default_url => "/assets/user/:style/placeholder.jpg",
      :url => "/system/user/:attachment/:id/:style/:filename",
      
      :path => ":rails_root/public/system/user/:attachment/:id/:style/:filename"
      
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/      
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/      

  has_many :objective_values
  has_many :user_objectives
  has_many :friends
  has_many :user_badges
  has_many :objective_comments
  
  
  validates_presence_of :name
  validates_presence_of :surname

  validates_uniqueness_of :email
  
  	def number_of_friends()
	  	return self.friends.length
	end
	
	def has_ownership?(objective_id)
		 self.user_objectives.where("objective_id=?", objective_id).present?
	end

end

reachagoal/app/models/user_badges.rb
class UserBadges < ActiveRecord::Base
	belongs_to :giver, :class_name => 'User', :foreign_key => 'giver_id'
	belongs_to :receiver, :class_name => 'User', :foreign_key => 'receiver_id'
	belongs_to :badge
end

reachagoal/app/models/user_objective.rb
class UserObjective < ActiveRecord::Base

  belongs_to :user
  belongs_to :objective

end

reachagoal/app/helpers/badges_helper.rb
module BadgesHelper
end

reachagoal/app/helpers/categories_helper.rb
module CategoriesHelper
end

reachagoal/app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

reachagoal/app/helpers/currencies_helper.rb
module CurrenciesHelper
end

reachagoal/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class='col-md-4 col-md-offset-4' id="error_explanation">
      <h1 class="h4">#{sentence}</h1>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

reachagoal/app/helpers/friends_helper.rb
module FriendsHelper
end

reachagoal/app/helpers/moneyboxes_helper.rb
module MoneyboxesHelper
end

reachagoal/app/helpers/private_helper.rb
module PrivateHelper
end

reachagoal/app/helpers/public_helper.rb
module PublicHelper
end

reachagoal/app/views/layouts/_challenge.html.erb
<div class='row' id="challenges">
	<% unless @challenges.blank?  %> 
		<% @challenges.reverse!.each do |userobj| %>
			<div class='col-md-4'>
				<%if (userobj.objective.completed_percentage<100) %>
					<div class='challenge'>
						<div class='challengeImage-wrapper'>
	            	<%= image_tag( userobj.objective.photo.url(:dashboard), :class => "challengeImage")%>
	            </div>
						<div class='black-wrapper'>
	              <div class='hiddenInfo'>
				  	<% if userobj.objective.objective_type != 0 %>

		                <div class='challengeFriends'>
		                	<% userobj.objective.user_objectives.reject{|c| c.user_id == current_user.id }.first(3).each do |line|%>
								<%unless line.user.id == current_user.id %>
									<%= link_to image_tag(line.user.photo.url(:nav), :class=>"img-responsive"), public_profile_path(line.user.id), :class => "friendPicture" %>
								<%end%>
							<%end%>
							<% if userobj.objective.user_objectives.length > 4 %>
								<a alt='Nome do amigo' class='friendPicture viewMore' href='javascript:;'><%= userobj.objective.user_objectives.length - 4 %></a>
							<% end %>
		                </div>
					<% end %>
					<div class='progressWrap'>
					  <h1 class='h6 progressTitle'>Progresso</h1>
					  	<% unless userobj.objective.objective_type == 1 %>
					    	<%= bootstrap_progress_bar(userobj.objective.completed_percentage, :color => 'info', :tiny => true) %>
					    <%else%>
					    	<%= bootstrap_progress_bar(userobj.objective.completed_percentage_shared(current_user.id), :color => 'info', :tiny => true)%>
					    <%end%>
					  <div class='challengeTotal'> <%= userobj.objective.price %> <%= t("currencyicon_html")%>  </div>
					</div>
	              </div>
	              
	              
	              
	            </div>
				<% else %>
					<div class='challenge completed'>
		                <div class='challengeImage-wrapper'>
		                	<%= image_tag( userobj.objective.photo.url(:dashboard), :class => "challengeImage")%>
		                </div>
						<div class='black-wrapper'>
		                  <div class='completedBadge'>
		                    <i class='fa fa-check fa-3x'></i>
		                  </div>
		                </div>
	            <%end%>
		            <div class='challengeTitle'>
		              <h1 class='h3'>
		              	<%= link_to userobj.objective.name, userobj.objective %>
		              </h1>
		            </div>
	          </div>
	        </div>
			
		<% end %>
		<div class='col-md-4'>
			<div class='challenge addNew'>
			  <%= link_to '<i class="fa fa-plus fa-4x"></i>'.html_safe, new_objective_path %>
			</div>
		</div>
	
		
	<% else %>
		<% if current_user.user_objectives.blank? %>
	
		<div class='col-md-12'>
		  <div class='noChallenges'>
		    <p>
		      Ainda não tens nenhum desafio. Porque não te aventuras e começas por
		      <%= link_to 'criar um novo desafio', new_objective_path %>
		      ?
		    </p>
		  </div>
		</div>
		
		<%else%>
			<div class='col-md-12'>
			  <div class='noChallenges'>
			    <p>
			      Ainda não tens nenhum desafio nesta categoria. Podes sempre <%= link_to 'criar um novo desafio', new_objective_path %>!
			    </p>
			  </div>
			</div>
		
		<% end %>
	
	<% end %>
	</div>
</div>

reachagoal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta content='IE=edge' http-equiv='X-UA-Compatible'>
  <meta content='width=device-width, initial-scale=1' name='viewport'>
  <title>Reachagoal</title>
  
  
  <%= stylesheet_link_tag    "typekit", media: "all" %>
  <%= stylesheet_link_tag    "fonts/reachagoal-custom.css", media: "all" %>
  <%= stylesheet_link_tag    "public", media: "all" %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  
  
  <%= javascript_include_tag 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %>
  <%= javascript_include_tag 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %>
  <%= csrf_meta_tags %>

  
</head>
<body>
    <nav class='navbar-wrapper navbar-default navbar-fixed-top' role='navigation'>
      <div class='container'>
        <div class='row'> 
     
		<!-- Begin logo-->
          <div class='col-md-4'>
            <div class='navbar-header'>
				<% if user_signed_in? %>
					<a class='logo' href='<%=dashboard_path %>'>
						<img alt='Reachagoal' src='/assets/logo.png'>
					</a>
				<% else %>
					<a class='logo' href='<%=root_path%>'>
						<img alt='Reachagoal' src='/assets/logo.png'>
					</a>
				<% end %>
            </div>
          </div>
		 <!--  End logo -->
		  
		  
		           
          <div class='col-md-8'>
            <div class='user-nav pull-right'>
              <ul class='nav navbar-nav'>
              	<% if user_signed_in? %>
			  		<% unless current_user.user_objectives.blank?%>
		                <li class='challenges'>						  
		                  <div class='title'>OS TEUS DESAFIOS</div>
		                  <div class='selectbox-wrapper'>
		                    <a data-toggle='dropdown' href='javascript:;'><%= (controller_name == "objectives" && action_name == "show" && @objective != nil) ? @objective.name : "Seleccionar desafio" %> <i class='fa fa-angle-down'></i></a>
	                    <div class='dropdown-menu dropdown-menu-right'>
	                      
	                      <div class='panel'>
	                        <ul class='list-group'>
	                        	<% current_user.user_objectives.reverse!.each do |userobj| %>


									<li <%if (controller_name == "objectives" && action_name == "show" && @objective != nil && !userobj.objective.blank? && userobj.objective.id == @objective.id) %> class='list-group-item active' <%else%> class='list-group-item' <%end%>>
										<%= link_to userobj.objective.name, userobj.objective %>
									</li>
								<% end %>                          
	                          <li class='list-group-item footer'>
	                            <%= link_to '<i class="fa fa-plus"></i> Criar desafio'.html_safe, new_objective_path %>
	                          </li>
	                        </ul>
	                    </div>
                    </div>
                  </div>
		                </li>
					<% else %>
		                <li class='newChallenge'>
		                  <div class='button-wrapper'>
		                     <%= link_to '<i class="fa fa-plus"></i> Começar desafio'.html_safe, new_objective_path %>
		                  </div>
		                </li>
					<% end %>
					<% if !current_user.user_objectives.blank? && !current_user.user_objectives.reject{ |c| c.objective.missing_value == 0}.blank? %>

		                <li class='mrPig'>
		                  <div class='inner-wrapper'>
		                    <a data-target='#mrPig-modal' data-toggle='modal' href='#'>
		                      <i class='icon icon-mrpig'></i>
		                    </a>
		                  </div>
		                </li>
		                
					<% end %>
	                <li class='notification'>
	                  <a data-toggle='dropdown' href='javascript:;'>
	                    <i class='fa fa-trophy'></i>
	                  </a>
	                  <div class='dropdown-menu cornered dropdown-menu-right'>
	                    <div class='panel'>
	                      <div class='panel-heading'>
	                        Progresso
	                      </div>
	                      <ul class='list-group'>
							<li class='list-group-item progress-neutral'>
							  <a class='unavailable' href='javascript:;'>
							    <p>
							      As notificações encontram-se indisponíveis neste momento.
							    </p>
							  </a>
							</li>
	                      </ul>
	                    </div>
	                  </div>
	                </li>
	                <li class='user-picture'>
	                  <a data-toggle='dropdown' href='javascript:;'>
	                    <%= image_tag current_user.photo.url(:nav)%>
	                  </a>
	                  <div class='dropdown-menu cornered dropdown-menu-right'>
	                    <div class='panel'>
	                      <ul class='list-group'>
	                        <li class='list-group-item'>
	                        <%= link_to "Definições", edit_user_registration_path   %>
							</li>
	                        <li class="list-group-item">
								<%= link_to "Sair", destroy_user_session_path, method: :delete   %>
	                        </li>
	                        <li class='list-group-item upgrade-link'>
	                          <a>Upgrade de conta <span class="badge"> BETA</span></a>
	                        </li>
	                        <li class='list-group-item'>
	                          <a href='javascript:;'>Ajuda</a>
	                        </li>
	                        <li class='list-group-item'>
	                          <a href='javascript:;'>Comunicar um problema</a>
	                        </li>
	                      </ul>
	                    </div>
	                  </div>
	                </li>
	                
                <% else %>
				  <!-- User not signed in-->
                  <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
				  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
                
              </ul>
              
            </div>
          </div>
        </div>
      </div>
    </nav>
	
		
	<% if user_signed_in? %>
		<% if !current_user.user_objectives.blank? && !current_user.user_objectives.reject{ |c| c.objective.missing_value == 0}.blank? %>

			<div aria-hidden='true' aria-labelledby='myModalLabel' class='modal fade' id='mrPig-modal' role='dialog' tabindex='-1'>
		      <div class='modal-dialog'>
		        <div class='modal-content'>
		          <div class='modal-header'>
		            <button class='close' data-dismiss='modal' type='button'>
		              <span aria-hidden='true'>&#215;</span>
		              <span class='sr-only'>Close</span>
		            </button>
		            <h1 class='h6 title'>
		              Adicionar poupança
		            </h1>
		          </div>
					<% id_obj = current_user.user_objectives.reverse!.reject{ |c| c.objective.missing_value == 0}.first().objective.id%>
					<%= form_tag "/objectives/#{id_obj}/add_value/", method: "post" do %>
					  	<div class='modal-body'>
					  		<%= hidden_field_tag :previous_page, "previous" %>				
							<div class='row'>
						<div class='form-group col-md-12'>
							<%= label_tag :obj, "Desafio a adicionar a poupança:" %>
							<%= select_tag :obj, options_from_collection_for_select( current_user.user_objectives.reverse!.reject{ |c| c.objective.missing_value == 0}.collect{ |c| c.objective}, "id", "name"), 
:class => 'form-control input-lg', :onchange => " $(this).closest('form').attr('action','/objectives/' + $(this).val() + '/add_value/')  "  %> 
						</div>
					</div>
							<div class='row'>
						<div class='form-group col-md-12'>
							<%= label_tag :value, t('howmanysave').capitalize %>
							<div class='wrapper'>
								<%= text_field_tag :value, "",class: 'form-control input-lg',  min: '1', placeholder: "10€"%>
								<i class='fa fa-2x fa-eur'></i>
							</div>
						</div>
					</div>
							<div class='row'>
						<div class='form-group col-md-12'>
						  <div class='wrapper'>
						  	<%= text_field_tag :description, "",class: 'form-control', placeholder: t('descriptionopt').capitalize %>
						  </div>
						</div>
						</div>
					</div>
						<div class='modal-footer'>
							<input class='btn btn-primary' type='submit' value="<%= t('add').capitalize %>"> </input>
						</div>
					<% end %>
		        </div>
		      </div>
		    </div>
		<%end%>
	<%end%>


	<% if notice %>
		<div class='alertWrapper'>
	      <div class='container'>
	        <div class='row'>
	          <div class='col-md-4 col-md-offset-4'>
	            <div class='alert alert-success alert-dismissible' role='alert'>
	              <button class='close' data-dismiss='alert' type='button'>
	                <span aria-hidden='true'>&#215;</span>
	              </button>
	              <%= notice.capitalize %>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	<% end %>
	<% if alert %>
		<div class='alertWrapper'>
	      <div class='container'>
	        <div class='row'>
	          <div class='col-md-4 col-md-offset-4'>
				 <div class='alert alert-warning alert-dismissible' role='alert'>
	              <button class='close' data-dismiss='alert' type='button'>
	                <span aria-hidden='true'>&#215;</span>
	              </button>
	              <strong>Ocorreu um erro.</strong>
				  <%= alert.capitalize %>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	<% end %>
	
	<%= yield %>
	
	<footer>
      <div class='container'>
        <div class='row'>
          <div class='col-md-6'>
            <p>
              Copyright
              <span class='bold'>Reachagoal</span>
              © 2014 All rights reserved.
            </p>
          </div>
          <div class='col-md-6'>
            <ul>
              <li>
                <a alt='Sobre nós' href='javascript:;'>Sobre nós</a>
              </li>
              <li>
                <a alt='Ajuda' href='javascript:;'>Ajuda</a>
              </li>
              <li>
                <a alt='Contacto' href='javascript:;'>Contacto</a>
              </li>
              <li>
                <a alt='Termos' href='javascript:;'>Termos</a>
              </li>
              <li>
                <a alt='Privacidade' href='javascript:;'>Privacidade</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    
	<%= javascript_include_tag "application" %>
	<%= yield :js %>
	
</body>
</html>

reachagoal/app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta content='IE=edge' http-equiv='X-UA-Compatible'>
  <meta content='width=device-width, initial-scale=1' name='viewport'>
  <title>Reachagoal</title>
  
  
  <%= stylesheet_link_tag    "typekit", media: "all" %>
  <%= stylesheet_link_tag    "fonts/reachagoal-custom.css", media: "all" %>
  <%= stylesheet_link_tag    "fonts/fontfacekit/facekit.css", media: "all" %>

  <%= stylesheet_link_tag    "public", media: "all" %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  
  <%= javascript_include_tag 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %>
  <%= javascript_include_tag 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %>
  <%= csrf_meta_tags %>

  
</head>
	<%= yield %>
	<% if notice %>
		<div class='alertWrapper'>
	      <div class='container'>
	        <div class='row'>
	          <div class='col-md-4 col-md-offset-4'>
	            <div class='alert alert-success alert-dismissible' role='alert'>
	              <button class='close' data-dismiss='alert' type='button'>
	                <span aria-hidden='true'>&#215;</span>
	              </button>
	              <%= notice.capitalize %>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	<% end %>
	<% if alert %>
		<div class='alertWrapper'>
	      <div class='container'>
	        <div class='row'>
	          <div class='col-md-4 col-md-offset-4'>
				 <div class='alert alert-warning alert-dismissible' role='alert'>
	              <button class='close' data-dismiss='alert' type='button'>
	                <span aria-hidden='true'>&#215;</span>
	              </button>
	              <strong>Ocorreu um erro.</strong>
				  <%= alert.capitalize %>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
	<% end %>
	

	
	<footer>
      <div class='container'>
        <div class='row'>
          <div class='col-md-6'>
            <p>
              Copyright
              <span class='bold'>Reachagoal</span>
              © 2014 All rights reserved.
            </p>
          </div>
          <div class='col-md-6'>
            <ul>
              <li>
                <a alt='Sobre nós' href='javascript:;'>Sobre nós</a>
              </li>
              <li>
                <a alt='Ajuda' href='javascript:;'>Ajuda</a>
              </li>
              <li>
                <a alt='Contacto' href='javascript:;'>Contacto</a>
              </li>
              <li>
                <a alt='Termos' href='javascript:;'>Termos</a>
              </li>
              <li>
                <a alt='Privacidade' href='javascript:;'>Privacidade</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    
	<%= javascript_include_tag "application" %>
	<%= yield :js %>
	
</body>
</html>