reachagoal/config/routes.rb
Reachagoal::Application.routes.draw do

  resources :currencies

  resources :moneyboxes

  resources :friends

  resources :categories

  devise_for :users
  
  resources :objectives, except: :index
  
  
  unauthenticated :user do
 	  root :to => "public#index", :as => "unauthenticated"
   end
 
  authenticated :user do
  	root :to => "private#user_dashboard" 
  end
  
  get "dashboard" => "private#user_dashboard"
  post "/objectives/:objective_id/add_value" => "objectives#add_value", :as => "add_value"
  post "/objectives/:objective_id/add_comment" => "objectives#add_comment", :as => "add_comment"
  post "/objectives/:objective_id/add_friend/:friend_id" => "objectives#add_friend", :as=>"add_friend_objective"


  get "remove_value/:id" => "objectives#remove_value", :as=>"remove_value"
  get "remove_comment/:id" => "objectives#remove_comment", :as=>"remove_comment"

  get "public/index" 
  

  get "publicprofile/:id" => "private#public_profile", :as=>"public_profile"

  post "publicprofile/add_badge/:friend_id" => "private#add_badge", :as=>"add_badge"

  post "add_friend/" => "private#add_friend", :as=>"add_friend_email"
  get "add_friend/:id" => "private#add_friend", :as=>"add_friend"
  get "remove_friend/:id" => "private#remove_friend", :as=>"remove_friend"
  
  get "ajax_challenges/:id" => "private#ajax_challenges"
  get "ajax_challenges" => "private#ajax_challenges"

  get "ajax_values/:id" => "objectives#ajax_values"
  get "ajax_badges/:id" => "private#ajax_badges"
  get "ajax_badges/" => "private#ajax_badges"
    
  get "ajax_friends/:id" => "private#ajax_friends"
  get "ajax_friends/" => "private#ajax_friends"
  
  
  
end

reachagoal/app/models/moneybox.rb
class Moneybox < ActiveRecord::Base
end

reachagoal/app/controllers/moneyboxes_controller.rb
class MoneyboxesController < ApplicationController
  before_action :set_moneybox, only: [:show, :edit, :update, :destroy]

  # GET /moneyboxes
  # GET /moneyboxes.json
  def index
    @moneyboxes = Moneybox.all
  end

  # GET /moneyboxes/1
  # GET /moneyboxes/1.json
  def show
  end

  # GET /moneyboxes/new
  def new
    @moneybox = Moneybox.new
  end

  # GET /moneyboxes/1/edit
  def edit
  end

  # POST /moneyboxes
  # POST /moneyboxes.json
  def create
    @moneybox = Moneybox.new(moneybox_params)

    respond_to do |format|
      if @moneybox.save
        format.html { redirect_to @moneybox, notice: 'Moneybox was successfully created.' }
        format.json { render action: 'show', status: :created, location: @moneybox }
      else
        format.html { render action: 'new' }
        format.json { render json: @moneybox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moneyboxes/1
  # PATCH/PUT /moneyboxes/1.json
  def update
    respond_to do |format|
      if @moneybox.update(moneybox_params)
        format.html { redirect_to @moneybox, notice: 'Moneybox was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @moneybox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moneyboxes/1
  # DELETE /moneyboxes/1.json
  def destroy
    @moneybox.destroy
    respond_to do |format|
      format.html { redirect_to moneyboxes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moneybox
      @moneybox = Moneybox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moneybox_params
      params.require(:moneybox).permit(:codenumber)
    end
end

reachagoal/app/helpers/moneyboxes_helper.rb
module MoneyboxesHelper
end

reachagoal/app/views/moneyboxes/_form.html.erb
<%= form_for(@moneybox) do |f| %>
  <% if @moneybox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moneybox.errors.count, "error") %> prohibited this moneybox from being saved:</h2>

      <ul>
      <% @moneybox.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codenumber %><br>
    <%= f.text_field :codenumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reachagoal/app/views/moneyboxes/edit.html.erb
<h1>Editing moneybox</h1>

<%= render 'form' %>

<%= link_to 'Show', @moneybox %> |
<%= link_to 'Back', moneyboxes_path %>

reachagoal/app/views/moneyboxes/index.html.erb
<h1>Listing moneyboxes</h1>

<table>
  <thead>
    <tr>
      <th>Codenumber</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @moneyboxes.each do |moneybox| %>
      <tr>
        <td><%= moneybox.codenumber %></td>
        <td><%= link_to 'Show', moneybox %></td>
        <td><%= link_to 'Edit', edit_moneybox_path(moneybox) %></td>
        <td><%= link_to 'Destroy', moneybox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moneybox', new_moneybox_path %>

reachagoal/app/views/moneyboxes/new.html.erb
<h1>New moneybox</h1>

<%= render 'form' %>

<%= link_to 'Back', moneyboxes_path %>

reachagoal/app/views/moneyboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codenumber:</strong>
  <%= @moneybox.codenumber %>
</p>

<%= link_to 'Edit', edit_moneybox_path(@moneybox) %> |
<%= link_to 'Back', moneyboxes_path %>